[workspace]
publish = false
dependencies_update = false
changelog_update = false    # we will use runtime package for changelogs


[[package]]
name = "oz-parachain-template-runtime"
changelog_update = true
changelog_path = "./CHANGELOG.md"
